version: '3.8'

services:
  music-player:
    build: .
    container_name: usb-music-player
    restart: unless-stopped
    
    # Network configuration
    network_mode: host
    
    # Environment variables
    environment:
      - CONTROL_FILE_NAME=playMusic.txt
      - WEB_PORT=5000
      - DEFAULT_VOLUME=70
      - PULSE_RUNTIME_PATH=/run/user/1000/pulse
    
    # Volume mounts
    volumes:
      # Native USB detection - make /media/pi read-write for better Docker compatibility
      - /media/pi:/media/pi:rw
      
      # Legacy mount points (remove when fully migrated)
      - /home/pi/usb:/home/pi/usb:rw
      - /mnt:/mnt:rw
      
      # Audio system access
      - /run/user/1000/pulse:/run/user/1000/pulse:rw
      - /dev/snd:/dev/snd:rw
      
      # USB device access for better detection
      - /dev/bus/usb:/dev/bus/usb:rw
      - /run/udev:/run/udev:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      
      # Mount table access for better mount detection
      - /proc/mounts:/proc/mounts:ro
      
      # Configuration persistence
      - ./config:/app/config:rw
      
      # Logs
      - ./logs:/app/logs:rw
    
    # Device access
    devices:
      - /dev/snd
    
    # Privileged mode for USB and audio access
    privileged: true
    
    # Add capabilities for mount detection
    cap_add:
      - SYS_ADMIN
      - DAC_OVERRIDE
        
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 